return {
	car_config=
	{
		[1]=
		{
			index = 1,
			id = 1,
			name = "发了力",
			car_name = "car_1",
			car_type = "DriveCarFaleli",
			car_skill_config_id = 1,
			big_youmen = 1,
			small_youmen = 2,
			sprint = 3,
			image_config = 1,
			tag_name = "跑车",
		},
		[2]=
		{
			index = 2,
			id = 2,
			name = "大脑斧",
			car_name = "car_2",
			car_type = "DriveCarTank",
			car_skill_config_id = 2,
			big_youmen = 4,
			small_youmen = 5,
			sprint = 6,
			image_config = 2,
			tag_name = "坦克",
		},
		[3]=
		{
			index = 3,
			id = 3,
			name = "平头哥",
			car_name = "car_3",
			car_type = "DriveCarPTG",
			car_skill_config_id = 2,
			big_youmen = 4,
			ptg_big_youmen = 8,
			ptg_attack = 7,
			small_youmen = 5,
			sprint = 6,
			image_config = 3,
			tag_name = "肌肉车",
		},
		[4]=
		{
			index = 4,
			id = 4,
			name = "地雷车",
			car_name = "car_4",
			car_type = "DriveCarLandmine",
			car_skill_config_id = 2,
			big_youmen = 4,
			small_youmen = 5,
			sprint = 6,
			image_config = 3,
			dlc_anzhuang_move = 5,
			tag_name = "战术车",
		},
	},
	image_config=
	{
		[1]=
		{
			index = 1,
			hall_img = "zjm_icon_fll",
			begin_panel_img = "com_icon_che_fll",
			game_top_img = "zd_icon_che_03",
		},
		[2]=
		{
			index = 2,
			hall_img = "zjm_icon_tk",
			begin_panel_img = "com_icon_che_tk",
			game_top_img = "zd_icon_che_01",
		},
		[3]=
		{
			index = 3,
			hall_img = "zjm_icon_ptg",
			game_top_img = "zd_icon_che_02",
		},
	},
	move_config=
	{
		[1]=
		{
			index = 1,
			id = 1,
			name = "大油门",
			type = "big_youmen",
			up_a = 20,
			down_a = 20,
			max_v = 35,
			min_v = 2.800000,
			random_min = 4,
			random_max = 7,
			max_move_num = 44,
			fx_type_config = {44,66,},
		},
		[2]=
		{
			index = 2,
			id = 2,
			name = "小油门",
			type = "small_youmen",
			up_a = 0,
			down_a = 0,
			max_v = 2.800000,
			min_v = 2.800000,
			random_min = 4,
			random_max = 7,
		},
		[3]=
		{
			index = 3,
			id = 3,
			name = "冲刺",
			type = "sprint",
			up_a = 100,
			down_a = 100,
			max_v = 65,
			min_v = 2.800000,
			random_min = 4,
			random_max = 7,
		},
		[4]=
		{
			index = 4,
			id = 4,
			name = "大油门",
			type = "big_youmen",
			up_a = 20,
			down_a = 20,
			max_v = 35,
			min_v = 2.800000,
			random_min = 4,
			random_max = 7,
			max_move_num = 44,
			fx_type_config = {44,66,},
		},
		[5]=
		{
			index = 5,
			id = 5,
			name = "小油门",
			type = "small_youmen",
			up_a = 0,
			down_a = 0,
			max_v = 2.800000,
			min_v = 2.800000,
			random_min = 4,
			random_max = 7,
		},
		[6]=
		{
			index = 6,
			id = 6,
			name = "冲刺",
			type = "sprint",
			up_a = 100,
			down_a = 100,
			max_v = 65,
			min_v = 2.800000,
			random_min = 4,
			random_max = 7,
		},
		[7]=
		{
			index = 7,
			id = 7,
			name = "平头哥撞击",
			type = "ptg_crash",
			up_a = 0,
			down_a = 0,
			max_v = 30,
			min_v = 30,
			random_min = 1,
			random_max = 2,
		},
		[8]=
		{
			index = 8,
			id = 8,
			name = "大油门",
			type = "ptg_big_youmen",
			up_a = 5,
			down_a = 0,
			max_v = 45,
			min_v = 45,
			random_min = 4,
			random_max = 7,
			max_move_num = 44,
			fx_type_config = {44,66,},
		},
	},
}